version: "0.75"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  connector:
    image: robot-ranger/mqtt-connector:latest
    container_name: connector
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mysql